### ISSUE TITLE
Merge with faker ?

### ISSUE THREAD

**Issue by sametmax** [omaciel/fauxfactory#84]
Hi,

There is a lib called "faker" that as been around for a long time, containing a lot of stuff with a nice extensible design. What about merging yours with it ?

**Comment by omaciel** [comment]
@sametmax hmmm I'm not sure... the data generated by fauxfactory is very specific to the automation of services that focus more on the functionality of the services themselves. For example, whereas faker would generate a random `address` value I'm more interested in the permutations of each field included in the `address` object and varying types of strings for each sub field (i.e. address1, address2, city, state, etc). I was aware of faker when I started this project but since I felt my need was a bit outside the provided functionality, I set out to create my own... Definitely worth the consideration, though, so thank you :)

**Comment by JacobCallahan** [comment]
@omaciel @sametmax I think it is best to keep the two separate, as it is easier for us to adapt to shifting requirements.
